require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PostingPortalsController do

  # This should return the minimal set of attributes required to create a valid
  # PostingPortal. As you add validations to PostingPortal, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PostingPortalsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all posting_portals as @posting_portals" do
      posting_portal = PostingPortal.create! valid_attributes
      get :index, {}, valid_session
      assigns(:posting_portals).should eq([posting_portal])
    end
  end

  describe "GET show" do
    it "assigns the requested posting_portal as @posting_portal" do
      posting_portal = PostingPortal.create! valid_attributes
      get :show, {:id => posting_portal.to_param}, valid_session
      assigns(:posting_portal).should eq(posting_portal)
    end
  end

  describe "GET new" do
    it "assigns a new posting_portal as @posting_portal" do
      get :new, {}, valid_session
      assigns(:posting_portal).should be_a_new(PostingPortal)
    end
  end

  describe "GET edit" do
    it "assigns the requested posting_portal as @posting_portal" do
      posting_portal = PostingPortal.create! valid_attributes
      get :edit, {:id => posting_portal.to_param}, valid_session
      assigns(:posting_portal).should eq(posting_portal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PostingPortal" do
        expect {
          post :create, {:posting_portal => valid_attributes}, valid_session
        }.to change(PostingPortal, :count).by(1)
      end

      it "assigns a newly created posting_portal as @posting_portal" do
        post :create, {:posting_portal => valid_attributes}, valid_session
        assigns(:posting_portal).should be_a(PostingPortal)
        assigns(:posting_portal).should be_persisted
      end

      it "redirects to the created posting_portal" do
        post :create, {:posting_portal => valid_attributes}, valid_session
        response.should redirect_to(PostingPortal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved posting_portal as @posting_portal" do
        # Trigger the behavior that occurs when invalid params are submitted
        PostingPortal.any_instance.stub(:save).and_return(false)
        post :create, {:posting_portal => {}}, valid_session
        assigns(:posting_portal).should be_a_new(PostingPortal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PostingPortal.any_instance.stub(:save).and_return(false)
        post :create, {:posting_portal => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested posting_portal" do
        posting_portal = PostingPortal.create! valid_attributes
        # Assuming there are no other posting_portals in the database, this
        # specifies that the PostingPortal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PostingPortal.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => posting_portal.to_param, :posting_portal => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested posting_portal as @posting_portal" do
        posting_portal = PostingPortal.create! valid_attributes
        put :update, {:id => posting_portal.to_param, :posting_portal => valid_attributes}, valid_session
        assigns(:posting_portal).should eq(posting_portal)
      end

      it "redirects to the posting_portal" do
        posting_portal = PostingPortal.create! valid_attributes
        put :update, {:id => posting_portal.to_param, :posting_portal => valid_attributes}, valid_session
        response.should redirect_to(posting_portal)
      end
    end

    describe "with invalid params" do
      it "assigns the posting_portal as @posting_portal" do
        posting_portal = PostingPortal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PostingPortal.any_instance.stub(:save).and_return(false)
        put :update, {:id => posting_portal.to_param, :posting_portal => {}}, valid_session
        assigns(:posting_portal).should eq(posting_portal)
      end

      it "re-renders the 'edit' template" do
        posting_portal = PostingPortal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PostingPortal.any_instance.stub(:save).and_return(false)
        put :update, {:id => posting_portal.to_param, :posting_portal => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested posting_portal" do
      posting_portal = PostingPortal.create! valid_attributes
      expect {
        delete :destroy, {:id => posting_portal.to_param}, valid_session
      }.to change(PostingPortal, :count).by(-1)
    end

    it "redirects to the posting_portals list" do
      posting_portal = PostingPortal.create! valid_attributes
      delete :destroy, {:id => posting_portal.to_param}, valid_session
      response.should redirect_to(posting_portals_url)
    end
  end

end
