require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeacherRolesController do

  # This should return the minimal set of attributes required to create a valid
  # TeacherRole. As you add validations to TeacherRole, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeacherRolesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all teacher_roles as @teacher_roles" do
      teacher_role = TeacherRole.create! valid_attributes
      get :index, {}, valid_session
      assigns(:teacher_roles).should eq([teacher_role])
    end
  end

  describe "GET show" do
    it "assigns the requested teacher_role as @teacher_role" do
      teacher_role = TeacherRole.create! valid_attributes
      get :show, {:id => teacher_role.to_param}, valid_session
      assigns(:teacher_role).should eq(teacher_role)
    end
  end

  describe "GET new" do
    it "assigns a new teacher_role as @teacher_role" do
      get :new, {}, valid_session
      assigns(:teacher_role).should be_a_new(TeacherRole)
    end
  end

  describe "GET edit" do
    it "assigns the requested teacher_role as @teacher_role" do
      teacher_role = TeacherRole.create! valid_attributes
      get :edit, {:id => teacher_role.to_param}, valid_session
      assigns(:teacher_role).should eq(teacher_role)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TeacherRole" do
        expect {
          post :create, {:teacher_role => valid_attributes}, valid_session
        }.to change(TeacherRole, :count).by(1)
      end

      it "assigns a newly created teacher_role as @teacher_role" do
        post :create, {:teacher_role => valid_attributes}, valid_session
        assigns(:teacher_role).should be_a(TeacherRole)
        assigns(:teacher_role).should be_persisted
      end

      it "redirects to the created teacher_role" do
        post :create, {:teacher_role => valid_attributes}, valid_session
        response.should redirect_to(TeacherRole.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved teacher_role as @teacher_role" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherRole.any_instance.stub(:save).and_return(false)
        post :create, {:teacher_role => {}}, valid_session
        assigns(:teacher_role).should be_a_new(TeacherRole)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherRole.any_instance.stub(:save).and_return(false)
        post :create, {:teacher_role => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested teacher_role" do
        teacher_role = TeacherRole.create! valid_attributes
        # Assuming there are no other teacher_roles in the database, this
        # specifies that the TeacherRole created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TeacherRole.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => teacher_role.to_param, :teacher_role => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested teacher_role as @teacher_role" do
        teacher_role = TeacherRole.create! valid_attributes
        put :update, {:id => teacher_role.to_param, :teacher_role => valid_attributes}, valid_session
        assigns(:teacher_role).should eq(teacher_role)
      end

      it "redirects to the teacher_role" do
        teacher_role = TeacherRole.create! valid_attributes
        put :update, {:id => teacher_role.to_param, :teacher_role => valid_attributes}, valid_session
        response.should redirect_to(teacher_role)
      end
    end

    describe "with invalid params" do
      it "assigns the teacher_role as @teacher_role" do
        teacher_role = TeacherRole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherRole.any_instance.stub(:save).and_return(false)
        put :update, {:id => teacher_role.to_param, :teacher_role => {}}, valid_session
        assigns(:teacher_role).should eq(teacher_role)
      end

      it "re-renders the 'edit' template" do
        teacher_role = TeacherRole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherRole.any_instance.stub(:save).and_return(false)
        put :update, {:id => teacher_role.to_param, :teacher_role => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested teacher_role" do
      teacher_role = TeacherRole.create! valid_attributes
      expect {
        delete :destroy, {:id => teacher_role.to_param}, valid_session
      }.to change(TeacherRole, :count).by(-1)
    end

    it "redirects to the teacher_roles list" do
      teacher_role = TeacherRole.create! valid_attributes
      delete :destroy, {:id => teacher_role.to_param}, valid_session
      response.should redirect_to(teacher_roles_url)
    end
  end

end
